---
- name: "playing iwth vars"
  hosts: all
  connection: local
  vars_files:
    - Details.yml
  tasks:
  - name: "printing the message"
    vars:
      NAME: "Swarup Kuamr"
    debug:
      msg:  "My name is {{ NAME }} and I am {{ Age }} years old and I am working as a {{ JOB }}"