---
- name: "checking datatypes"
  hosts: all
  connection: local
  vars: 
    IS_LIVE: true
  tasks:
    - name: " if it is live or not"
      debug:
        msg: "the server is live"
      when: IS_LIVE == true  
  tasks:
    - name: "printing facts"
      debug:
        msg: "{{ ansible_facts }}"