---
- name: "Difference bewteen shell and command moduele"
  hosts: all
  connection: local
  tasks:
  - name: "checking shell module"
    shell: cat /etc/passwd | grep root
    register: useroutput
  - name: "printing the output"
    debug:
      msg: "{{ useroutput.stdout }}"
  - name: "checking shell module"
    shell: ls -ltr > files
    register: lsoutput
  - name: "printing the output"
    debug:
      msg: "the file is created here is the output {{ lsoutput.rc }}"
  
  