---
- name: "installing packages with loops"
  hosts: all
  become: yes
  tasks:
    - name: "installing packages"
      yum: name: "{{ item }} state: present"
      loop:
        - nginx
        - httpd