---
- name: " demo on error handling"
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: "checking user exists or not"
      command: id swarup
      register: result
      ignore_errors: yes
    
    - name: "printing the result"
      debug:
        msg: "{{ result.stdout }}"
    
    - name: "create user"
      command: useradd swarup
      when: result.rc != 0